services:
  - type: web
    name: bugema-scholarship-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "api.admin_api:app" --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: FLASK_ENV
        value: production
